SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/../.." && pwd)
RUNTIME_DIR=${INSTALL_FOLDER:-"$ROOT_DIR/pglite/out/native"}
SDK_DIR=${SDK_DIR:-"$RUNTIME_DIR/psycopg2-sdk"}
WORK_DIR=${WORK_DIR:-"$ROOT_DIR/pglite/out/upstream-psycopg2"}
PSYCOPG2_VERSION=${PSYCOPG2_VERSION:-2.9.10}
PYTHON_BIN=${PYTHON_BIN:-python3}
SOURCE_DIR="$WORK_DIR/src/psycopg2-$PSYCOPG2_VERSION"
VENV_DIR="$WORK_DIR/venv"
DOWNLOAD_DIR="$WORK_DIR/download"
DATA_DIR="$WORK_DIR/pgdata"
PATCH_DIR="$SCRIPT_DIR/patches"
PATHLIKE_PATCH="$PATCH_DIR/psycopg2-$PSYCOPG2_VERSION-pathlike.patch"
DISTNAME_PATCH="$PATCH_DIR/psycopg2-$PSYCOPG2_VERSION-pglite-dist.patch"
DARWIN_OPENSSL_PATCH="$PATCH_DIR/psycopg2-$PSYCOPG2_VERSION-darwin-openssl.patch"
WHEEL_DIR="$WORK_DIR/wheelhouse"
PSYCOPG2_SDIST_URL=${PSYCOPG2_SDIST_URL:-"https://files.pythonhosted.org/packages/source/p/psycopg2/psycopg2-$PSYCOPG2_VERSION.tar.gz"}
SDIST_PATH="$DOWNLOAD_DIR/psycopg2-$PSYCOPG2_VERSION.tar.gz"
